/* ============================================================
   MELVYN CROSS — CONTENT LAYER  (auto-generated)
   Generated by scripts/fetch-content.js at build time.
   Source: https://p4gxllem.sanity.studio
   DO NOT edit this file directly — edit content in Sanity Studio.
   ============================================================ */

const content = {
  en: {
    /* ── NAV ── */
    nav_location: "<span class=\"nav__dot\"></span>Lille",

    /* ── 01. HERO ── */
    hero_label: "An E-commerce Expert, currently in transit.",
    hero_word_1: "Melvyn",
    hero_word_2: "<em>Cross</em>",
    hero_caption_1: "I spent six years building a E-commerce storefront from nothing\u00a0into a <strong>\u20ac1,600,000</strong>\u00a0per\u00a0year European e-commerce business.",
    hero_caption_2: "I\u2019m now looking for the next one.",

    /* ── 02. THE NUMBER ── */
    number_label: "The result, before the story",
    number_year: "Nov 2020 \u2192 Sept 2026",
    number_target: 1600000,
    number_caption: "Average annual revenue of <em>planetsoarshop.com</em>, a photovoltaic e-commerce I built and ran as the sole e-commerce lead.",

    /* ── 03. THE BEGINNING ── */
    beginning_chapter: "Chapter I",
    beginning_chapter_name: "The Beginning",
    beginning_title: "November <em>2020</em>.",
    beginning_lead: "No storefront. No catalogue. No suppliers. A company that wanted to sell solar online and didn\u2019t yet know how.",
    beginning_p1: "I joined Planet Soar as their e-commerce lead. Within months I had a temporary contract turn into an apprenticeship, and an apprenticeship turn into the build of <em>planetsoarshop.com</em>. What started as a side channel became the company\u2019s commercial engine.",
    beginning_p2: "Six years later, the online channel accounts for <strong>60% of revenue</strong> and sources <strong>100% of inbound demand</strong>. It is a story about scale, but also about <em>protecting</em> what works while everything around it changes.",

    /* ── 04. WHAT I BUILT ── */
    built_chapter: "Chapter II",
    built_title: "What <em>I</em> built.",
    built_intro: "A Shopify storefront with 544 active SKUs at peak, served by nine European suppliers, supported by a custom shipping engine, and run by a team of seven.",
    stat_1_label: "SKUs at catalogue peak",
    stat_1_note: "Panels, batteries, inverters, EV chargers, accessories. Five categories, each with their own logistics constraints.",
    stat_2_label: "European suppliers onboarded",
    stat_2_note: "ENECSOL, VOLTANEO, KRANNICH, BAYWARE, ESTG, POWR CONNECT, ALLIANTZ, plus two irregular partners in Switzerland and Italy.",
    stat_3_label: "Shipping profiles, hand-built",
    stat_3_note: "The problem nobody wanted to solve: per-item shipping across nine suppliers with no carrier API. I built an internal cost model with <strong>~90% accuracy</strong>.",
    stat_4_label: "Daily organic impressions at peak",
    stat_4_note: "~500 daily clicks, 2.5% CTR. All organic SEO. Paid was reserved for product launches and peak seasons only.",
    stat_5_label: "People on the team",
    stat_5_note: "Five sales representatives, one e-commerce assistant, plus oversight of the accounting function. KPIs, reporting cadence, process design.",
    stat_6_label: "Revenue through the online channel",
    stat_6_note: "Quotation funnel above \u20ac7,000. Direct conversion below. A deliberate split for a high-AOV catalogue, not a workaround.",

    /* ── 05. THE DEALS ── */
    deals_chapter: "Chapter III",
    deals_title: "Two deals <em>I</em> closed.",
    deal_1_route: "Lille \u2192 Miami",
    deal_1_name: "Sunpowered Yachts",
    deal_1_story: "120 SunPower panels, shipped internationally from France to Miami, Florida. End-to-end ownership of the deal: quotation, negotiation, logistics, shipping organisation.",
    deal_2_route: "Lille \u2192 France",
    deal_2_name: "EURL FCE28",
    deal_2_story: "Domestic enterprise account. A different funnel: longer cycle, technical discussion, supplier coordination. Same outcome.",

    /* ── 06. FASEP ── */
    fasep_chapter: "Chapter IV",
    fasep_when: "Oct 17 \u2014 Nov 1, 2025",
    fasep_title: "A two-week mission to <em>Southern Africa</em>.",
    fasep_lead: "Planet Soar was bidding on a European Union <strong>FASEP public-sector contract</strong> in Southern Africa. The bid needed local partners on the ground.",
    fasep_p1: "I flew to Gaborone and Johannesburg. Two weeks of meetings, site visits, partnership conversations. By the end, we had secured <strong>Solar Power Kgalagadi Resources Development Co.</strong> as the local partner underpinning the bid.",
    fasep_aside: "It is the part of the job that is rarely on the e-commerce manager\u2019s brief. I think that\u2019s why it matters.",

    /* ── 07. WHAT I BRING ── */
    bring_chapter: "Chapter V",
    bring_title: "What I bring to <em>your</em> next thing.",
    bring_col1_title: "The Stack",
    bring_col2_title: "The Range",
    bring_col3_title: "The Edges",

    /* ── 08. CONTACT ── */
    contact_pre: "If you\u2019ve made it this far",
    contact_cta: "Let\u2019s <em>talk</em>.",
    contact_cv: "Download CV (PDF)",

    /* ── FOOTER ── */
    foot_built: "Built in Lille. Hosted on Vercel.",

    /* ── PORTRAIT ── */
    portrait_alt: "Melvyn Cross",
    portrait_placeholder: "Add portrait.jpg to /img/",

    /* ── EDUCATION PAGE ── */
    edu_hero_pre: "Academic journey",
    edu_hero_title: "My <em>education</em>.",
    edu_hero_sub: "From Botswana to Paris \u2014 a path built on curiosity, commerce, and three years of learning inside a live business.",
    edu_hero_stat1_num: "2",
    edu_hero_stat1_txt: "French institutions",
    edu_hero_stat2_num: "Bac+5",
    edu_hero_stat2_txt: "Highest level",
    edu_hero_stat3_num: "3 yrs",
    edu_hero_stat3_txt: "Apprenticeship",
    edu_isg_program: "MSc Brand Management &amp; e-Business \u2014 Bac+5",
    edu_isg_dates: "Sept 2024 \u2013 Sept 2026",
    edu_isg_grade: "~15 / 20",
    edu_isg_desc1: "A Bac+5 programme at one of France's leading business schools, centred on building brand strategy and e-business capability in an international environment. The curriculum bridges classical management thinking with the full stack of modern digital commerce \u2014 from corporate strategy down to conversion optimisation and no-code tooling.",
    edu_isg_desc2: "My thesis project is a complete business plan for a new B2C e-commerce venture, beginning from a \u20ac15,000 capital position \u2014 applying every module in a real decision-making context.",
    edu_isg_opinion: "ISG gave me a vocabulary I was missing. Not just e-commerce tactics, but brand architecture, long-term positioning, and the strategic thinking that separates businesses that scale from ones that plateau. I apply it every time I'm deciding whether to chase a short-term margin or protect a brand signal.",
    edu_isg_modules: "Corporate Strategy, Business Development, Digital Transformation, Cross-Channel Strategy, Conversion & Retention, No-Code Tools, MIS, Brand Architecture, E-Business Strategy",
    edu_iut_program: "BUT Marketing Digital, e-Business &amp; Entrepreneuriat \u2014 Bac+3",
    edu_iut_dates: "Sept 2021 \u2013 Sept 2024",
    edu_iut_employer: "Planet Soar Shop",
    edu_iut_desc1: "A three-year work-study degree combining rigorous academic marketing with a full-time apprenticeship at Planet Soar Shop. From day one, every concept had a live application \u2014 managing SEO, running paid campaigns, and operating e-commerce at scale, all while earning the degree.",
    edu_iut_desc2: "This is where the foundation was built that eventually took Planet Soar Shop from start-up to \u20ac1.6M in annual revenue. Not in simulation. In production.",
    edu_iut_opinion: "The alternance stripped away the safety net. Every model I built on a Monday was pressure-tested by Thursday's results. It taught me that the fastest way to truly learn something is to have real consequences attached \u2014 and that instinct for reading performance data quickly is still what I rely on most today.",
    edu_iut_modules: "Digital Marketing, SEO / SEA, E-commerce Operations, Entrepreneurship, Data Analytics, Content Strategy, Brand Management, UX & CRO, Project Management",
    edu_gss_desc: "International secondary education completed in Botswana before relocating to France for higher studies. Growing up navigating two continents \u2014 Africa and Europe \u2014 built an instinct for adapting across markets, cultures, and communication styles that I carry into every professional context today.",

    /* ── QUALIFICATIONS PAGE ── */
    qua_hero_pre: "Professional credentials",
    qua_hero_title: "My <em>qualifications</em>.",
    qua_hero_sub: "Certified skills that back the work \u2014 from CRM management and analytics to project delivery. Plus one more on the way.",
    qua_hero_stat1_num: "2",
    qua_hero_stat1_txt: "Active certifications",
    qua_hero_stat2_num: "1",
    qua_hero_stat2_txt: "In progress",
    qua_hero_stat3_num: "3+",
    qua_hero_stat3_txt: "Platforms covered",
    qua_hs_name: "Digital Marketing Certified",
    qua_hs_skills: "CRM Management, Lead Nurturing, Email Marketing, Sales Pipeline, Inbound Strategy, Contact Segmentation",
    qua_ga_name: "Google Analytics (GA4) Certification",
    qua_ga_skills: "GA4, Conversion Tracking, Audience Analysis, E-commerce Reports, UTM Parameters, Data Studio",
    qua_pmi_name: "PMI Project Management Professional",
    qua_pmi_status: "Coming soon",
    qua_pmi_skills: "Project Planning, Risk Management, Agile / Scrum, Stakeholder Mgmt, Budget Control, Sprint Planning",

    /* ── CONTACT PAGE ── */
    cp_hero_pre: "Let's connect",
    cp_hero_title: "Get in <em>touch</em>.",
    cp_email: "melvyn.cross05@gmail.com",
    cp_linkedin: "/in/melvyn-botlhe",
    cp_linkedin_url: "https://www.linkedin.com/in/melvyn-botlhe",
    cp_phone: "+33 6 22 52 70 79",
    cp_phone_url: "+33622527079",

    /* ── BLOG PAGE ── */
    bl_hero_title: "Stories &amp; <em>Ideas</em>.",
    bl_hero_desc: "Where I write about e-commerce strategy, what AI is actually changing, and what the market is doing when no one's looking.",

    /* ── EDITORIAL SECTIONS ── */
    bl_editorial: "<p>The Dispatch exists because the topics that shape e-commerce — AI-driven personalisation, platform economics, shifting consumer behaviour, the slow collapse of third-party cookies — move faster than most coverage keeps up with. I follow them closely because they directly determine what works and what breaks in the online businesses I build and run.</p><p>These articles are how I process what I'm watching: the signal inside the noise, the strategies worth keeping, and the assumptions the market is quietly discarding. I don't write to cover everything. I write when something is worth getting right.</p>",
    edu_editorial: "<p>My academic path was built around a single constraint: every theory needed a live application within weeks. Joining IUT de Lens the same year I started at Planet Soar wasn't a scheduling coincidence — it was the point. Three years of work-study compressed what most programmes spread across five, and the pressure of real commercial consequences made the learning stick in a way that a classroom alone cannot replicate.</p><p>The move to ISG Paris came at the right moment. The apprenticeship had given me execution depth; the MSc gave me the strategic vocabulary to frame what I'd built and plan what comes next. The thesis project — a full business plan for a B2C e-commerce venture from a €15,000 starting position — is not an academic exercise. It's the blueprint I intend to use.</p><p>From Botswana, where I completed secondary school, to Lens, to Paris: the geography changed but the logic didn't. Each step was chosen because it closed a specific gap.</p>",
    qua_editorial: "<p>I pursue certifications for a specific reason: structured learning forces me to systematise knowledge I've often acquired intuitively, and that process of formalisation exposes gaps I didn't know I had.</p><p>The HubSpot Digital Marketing certification changed how I think about the full funnel — not just traffic acquisition but the entire chain from first contact to closed deal. The Google Analytics (GA4) certification made me a more rigorous analyst; being tested on the methodology rather than just the interface meant I had to understand why the numbers move, not just how to read them. The PMI certification I'm working towards is about project delivery — because managing cross-functional launches has taught me that a clear framework is the difference between a release that lands and one that drifts.</p><p>Beyond the credentials, the discipline itself matters. Committing to structured study while running a live operation sharpens your relationship with your own knowledge — you learn what you actually understand versus what you've just seen work before.</p>",
  },

  fr: {
    /* ── NAV ── */
    nav_location: "<span class=\"nav__dot\"></span>Lille",

    /* ── 01. HERO ── */
    hero_label: "Un Expert E-commerce, en transit.",
    hero_word_1: "Melvyn",
    hero_word_2: "<em>Cross</em>",
    hero_caption_1: "J\u2019ai pass\u00e9 six ans \u00e0 construire une E-commerce de z\u00e9ro jusqu\u2019\u00e0 <strong>1\u00a0600\u00a0000\u00a0\u20ac</strong> de chiffre d\u2019affaires annuel en Europe.",
    hero_caption_2: "Je cherche maintenant le prochain projet.",

    /* ── 02. THE NUMBER ── */
    number_label: "Le r\u00e9sultat, avant l\u2019histoire",
    number_year: "Nov 2020 \u2192 Sept 2026",
    number_target: 1600000,
    number_caption: "Chiffre d\u2019affaires annuel moyen de <em>planetsoarshop.com</em>, un e-commerce photovolta\u00efque que j\u2019ai construit et g\u00e9r\u00e9 en tant que seul responsable e-commerce.",

    /* ── 03. THE BEGINNING ── */
    beginning_chapter: "Chapitre I",
    beginning_chapter_name: "Le D\u00e9but",
    beginning_title: "Novembre <em>2020</em>.",
    beginning_lead: "Pas de boutique. Pas de catalogue. Pas de fournisseurs. Une entreprise qui voulait vendre du solaire en ligne et ne savait pas encore comment.",
    beginning_p1: "J\u2019ai rejoint Planet Soar en tant que responsable e-commerce. En quelques mois, un contrat temporaire est devenu une alternance, et cette alternance est devenue la construction de <em>planetsoarshop.com</em>. Ce qui a commenc\u00e9 comme un canal secondaire est devenu le moteur commercial de l\u2019entreprise.",
    beginning_p2: "Six ans plus tard, le canal en ligne repr\u00e9sente <strong>60\u00a0% du chiffre d\u2019affaires</strong> et g\u00e9n\u00e8re <strong>100\u00a0% de la demande entrante</strong>. C\u2019est une histoire de croissance, mais aussi de <em>protection</em> de ce qui fonctionne pendant que tout change autour.",

    /* ── 04. WHAT I BUILT ── */
    built_chapter: "Chapitre II",
    built_title: "Ce que <em>j\u2019ai</em> construit.",
    built_intro: "Une boutique Shopify avec 544 SKU actifs au pic, approvisionn\u00e9e par neuf fournisseurs europ\u00e9ens, soutenue par un moteur de livraison sur mesure, et g\u00e9r\u00e9e par une \u00e9quipe de sept personnes.",
    stat_1_label: "SKU au pic du catalogue",
    stat_1_note: "Panneaux, batteries, onduleurs, bornes de recharge, accessoires. Cinq cat\u00e9gories, chacune avec ses propres contraintes logistiques.",
    stat_2_label: "Fournisseurs europ\u00e9ens int\u00e9gr\u00e9s",
    stat_2_note: "ENECSOL, VOLTANEO, KRANNICH, BAYWARE, ESTG, POWR CONNECT, ALLIANTZ, plus deux partenaires ponctuels en Suisse et en Italie.",
    stat_3_label: "Profils de livraison construits manuellement",
    stat_3_note: "Le probl\u00e8me que personne ne voulait r\u00e9soudre : la livraison par article chez neuf fournisseurs sans API transporteur. J\u2019ai construit un mod\u00e8le de co\u00fbt interne avec <strong>~90\u00a0% de pr\u00e9cision</strong>.",
    stat_4_label: "Impressions organiques quotidiennes au pic",
    stat_4_note: "~500 clics par jour, 2,5\u00a0% de CTR. 100\u00a0% SEO organique. Le pay\u00e9 \u00e9tait r\u00e9serv\u00e9 aux lancements de produits et aux pics saisonniers.",
    stat_5_label: "Personnes dans l\u2019\u00e9quipe",
    stat_5_note: "Cinq commerciaux, un assistant e-commerce, plus la supervision de la fonction comptable. KPIs, cadence de reporting, conception de processus.",
    stat_6_label: "Chiffre d\u2019affaires via le canal en ligne",
    stat_6_note: "Tunnel de devis au-dessus de 7\u00a0000\u00a0\u20ac. Conversion directe en dessous. Une r\u00e9partition d\u00e9lib\u00e9r\u00e9e pour un catalogue \u00e0 panier \u00e9lev\u00e9, pas un contournement.",

    /* ── 05. THE DEALS ── */
    deals_chapter: "Chapitre III",
    deals_title: "Deux deals <em>que j\u2019ai</em> conclus.",
    deal_1_route: "Lille \u2192 Miami",
    deal_1_name: "Sunpowered Yachts",
    deal_1_story: "120 panneaux SunPower, exp\u00e9di\u00e9s internationalement de France \u00e0 Miami, en Floride. Pilotage de bout en bout : devis, n\u00e9gociation, logistique, organisation de l\u2019exp\u00e9dition.",
    deal_2_route: "Lille \u2192 France",
    deal_2_name: "EURL FCE28",
    deal_2_story: "Compte entreprise domestique. Un cycle diff\u00e9rent : plus long, discussions techniques, coordination fournisseurs. M\u00eame r\u00e9sultat.",

    /* ── 06. FASEP ── */
    fasep_chapter: "Chapitre IV",
    fasep_when: "17 oct. \u2014 1er nov. 2025",
    fasep_title: "Une mission de deux semaines en <em>Afrique australe</em>.",
    fasep_lead: "Planet Soar r\u00e9pondait \u00e0 un <strong>appel d\u2019offres FASEP du secteur public</strong> de l\u2019Union europ\u00e9enne en Afrique australe. L\u2019offre n\u00e9cessitait des partenaires locaux sur le terrain.",
    fasep_p1: "Je me suis rendu \u00e0 Gaborone et Johannesburg. Deux semaines de r\u00e9unions, de visites de sites, de conversations partenariales. Au final, nous avions s\u00e9curis\u00e9 <strong>Solar Power Kgalagadi Resources Development Co.</strong> comme partenaire local pour soutenir l\u2019offre.",
    fasep_aside: "C\u2019est la partie du travail qui figure rarement dans la fiche de poste du responsable e-commerce. C\u2019est pour \u00e7a qu\u2019elle compte.",

    /* ── 07. WHAT I BRING ── */
    bring_chapter: "Chapitre V",
    bring_title: "Ce que j\u2019apporte \u00e0 <em>votre</em> prochain projet.",
    bring_col1_title: "L\u2019Arsenal",
    bring_col2_title: "Le Spectre",
    bring_col3_title: "Les Atouts",

    /* ── 08. CONTACT ── */
    contact_pre: "Si vous \u00eates arriv\u00e9 jusqu\u2019ici",
    contact_cta: "Parlons-<em>en</em>.",
    contact_cv: "T\u00e9l\u00e9charger le CV (PDF)",

    /* ── FOOTER ── */
    foot_built: "Construit \u00e0 Lille. H\u00e9berg\u00e9 sur Vercel.",

    /* ── PORTRAIT ── */
    portrait_alt: "Melvyn Cross",
    portrait_placeholder: "Ajouter portrait.jpg dans /img/",

    /* ── EDUCATION PAGE ── */
    edu_hero_pre: "Parcours acad\u00e9mique",
    edu_hero_title: "Mon <em>parcours \u00e9ducatif</em>.",
    edu_hero_sub: "Du Botswana \u00e0 Paris \u2014 un chemin construit sur la curiosit\u00e9, le commerce et trois ann\u00e9es d'apprentissage au c\u0153ur d'une entreprise r\u00e9elle.",
    edu_hero_stat1_num: "2",
    edu_hero_stat1_txt: "\u00c9tablissements fran\u00e7ais",
    edu_hero_stat2_num: "Bac+5",
    edu_hero_stat2_txt: "Niveau le plus \u00e9lev\u00e9",
    edu_hero_stat3_num: "3 ans",
    edu_hero_stat3_txt: "Alternance",
    edu_isg_program: "Master Management de Marque & e-Business \u2014 Bac+5",
    edu_isg_dates: "Sept 2024 \u2013 Sept 2026",
    edu_isg_grade: "~15 / 20",
    edu_isg_desc1: "Un programme Bac+5 dans l'une des plus grandes \u00e9coles de commerce fran\u00e7aises, centr\u00e9 sur le d\u00e9veloppement de la strat\u00e9gie de marque et des comp\u00e9tences en e-business dans un environnement international. Le cursus fait le lien entre les fondements classiques du management et l'ensemble des outils du commerce digital moderne \u2014 de la strat\u00e9gie d'entreprise jusqu'\u00e0 l'optimisation de la conversion et les outils no-code.",
    edu_isg_desc2: "Mon projet de th\u00e8se est un business plan complet pour une nouvelle entreprise e-commerce B2C, \u00e0 partir d'un capital initial de 15 000 \u20ac \u2014 en appliquant chaque module dans un contexte de prise de d\u00e9cision r\u00e9el.",
    edu_isg_opinion: "L'ISG m'a donn\u00e9 un vocabulaire qui me manquait. Pas seulement des tactiques e-commerce, mais l'architecture de marque, le positionnement \u00e0 long terme, et la pens\u00e9e strat\u00e9gique qui s\u00e9pare les entreprises qui se d\u00e9veloppent de celles qui stagnent. J'applique cela \u00e0 chaque fois que je dois d\u00e9cider entre chercher une marge \u00e0 court terme ou pr\u00e9server le signal de ma marque.",
    edu_isg_modules: "Strat\u00e9gie d'entreprise, D\u00e9veloppement commercial, Transformation digitale, Strat\u00e9gie cross-canal, Conversion & r\u00e9tention, Outils no-code, SI, Architecture de marque, Strat\u00e9gie e-business",
    edu_iut_program: "BUT Marketing Digital, e-Business & Entrepreneuriat \u2014 Bac+3",
    edu_iut_dates: "Sept 2021 \u2013 Sept 2024",
    edu_iut_employer: "Planet Soar Shop",
    edu_iut_desc1: "Un dipl\u00f4me en alternance de trois ans alliant un enseignement acad\u00e9mique rigoureux du marketing \u00e0 une formation en apprentissage \u00e0 temps plein chez Planet Soar Shop. D\u00e8s le premier jour, chaque concept trouvait une application concr\u00e8te \u2014 gestion du SEO, campagnes publicitaires, et op\u00e9ration du e-commerce \u00e0 grande \u00e9chelle, tout en obtenant le dipl\u00f4me.",
    edu_iut_desc2: "C'est ici qu'ont \u00e9t\u00e9 pos\u00e9es les fondations qui ont men\u00e9 Planet Soar Shop d'une start-up \u00e0 1,6 M\u20ac de chiffre d'affaires annuel. Pas en simulation. En production.",
    edu_iut_opinion: "L'alternance a supprim\u00e9 le filet de s\u00e9curit\u00e9. Chaque mod\u00e8le construit le lundi \u00e9tait test\u00e9 par les r\u00e9sultats du jeudi. Cela m'a appris que le moyen le plus rapide d'apprendre vraiment quelque chose est d'avoir de vraies cons\u00e9quences attach\u00e9es \u2014 et que cet instinct pour lire rapidement les donn\u00e9es de performance est toujours ce sur quoi je m'appuie le plus aujourd'hui.",
    edu_iut_modules: "Marketing digital, SEO / SEA, Op\u00e9rations e-commerce, Entrepreneuriat, Analyse de donn\u00e9es, Strat\u00e9gie de contenu, Gestion de marque, UX & CRO, Gestion de projet",
    edu_gss_desc: "Formation secondaire internationale suivie au Botswana avant de d\u00e9m\u00e9nager en France pour des \u00e9tudes sup\u00e9rieures. Avoir grandi en naviguant entre deux continents \u2014 l'Afrique et l'Europe \u2014 a forg\u00e9 un instinct d'adaptation aux diff\u00e9rents march\u00e9s, cultures et styles de communication que je mets en \u0153uvre dans chaque contexte professionnel aujourd'hui.",

    /* ── QUALIFICATIONS PAGE ── */
    qua_hero_pre: "Certifications professionnelles",
    qua_hero_title: "Mes <em>qualifications</em>.",
    qua_hero_sub: "Comp\u00e9tences certifi\u00e9es qui soutiennent le travail \u2014 de la gestion CRM et l'analyse \u00e0 la livraison de projets. Et une de plus en route.",
    qua_hero_stat1_num: "2",
    qua_hero_stat1_txt: "Certifications actives",
    qua_hero_stat2_num: "1",
    qua_hero_stat2_txt: "En cours",
    qua_hero_stat3_num: "3+",
    qua_hero_stat3_txt: "Plateformes couvertes",
    qua_hs_name: "Certifi\u00e9 en marketing num\u00e9rique",
    qua_hs_skills: "Gestion CRM, Nurturing de leads, Email marketing, Pipeline de vente, Strat\u00e9gie inbound, Segmentation de contacts",
    qua_ga_name: "Certification Google Analytics (GA4)",
    qua_ga_skills: "GA4, Suivi des conversions, Analyse d'audience, Rapports e-commerce, Param\u00e8tres UTM, Data Studio",
    qua_pmi_name: "PMI Project Management Professional (PMP)",
    qua_pmi_status: "Prochainement",
    qua_pmi_skills: "Planification de projets, Gestion des risques, Agile / Scrum, Gestion des parties prenantes, Contr\u00f4le budg\u00e9taire, Planification de sprints",

    /* ── CONTACT PAGE ── */
    cp_hero_pre: "Entrez en contact",
    cp_hero_title: "contactez- <em>moi</em>.",
    cp_email: "melvyn.cross05@gmail.com",
    cp_linkedin: "/in/melvyn-botlhe",
    cp_linkedin_url: "https://www.linkedin.com/in/melvyn-botlhe",
    cp_phone: "+33 6 22 52 70 79",
    cp_phone_url: "+33622527079",

    /* ── BLOG PAGE ── */
    bl_hero_title: "Stories &amp; <em>Ideas</em>.",
    bl_hero_desc: "C'est ici que j'aborde la strat\u00e9gie E-commerce, ce que l'IA est en train de changer concr\u00e8tement, et ce que fait le march\u00e9 quand personne ne regarde.",

    /* \u2500\u2500 EDITORIAL SECTIONS \u2500\u2500 */
    bl_editorial: "<p>The Dispatch existe parce que les sujets qui fa\u00e7onnent l'e-commerce \u2014 la personnalisation pilot\u00e9e par l'IA, l'\u00e9conomie des plateformes, l'\u00e9volution du comportement des consommateurs, la disparition progressive des cookies tiers \u2014 \u00e9voluent plus vite que la plupart des analyses ne le suivent. Je les suis de pr\u00e8s parce qu'ils d\u00e9terminent directement ce qui fonctionne et ce qui casse dans les entreprises en ligne que je construis et g\u00e8re.</p><p>Ces articles sont ma fa\u00e7on de dig\u00e9rer ce que j'observe : le signal dans le bruit, les strat\u00e9gies qui m\u00e9ritent d'\u00eatre conserv\u00e9es, et les hypoth\u00e8ses que le march\u00e9 abandonne discr\u00e8tement. Je n'\u00e9cris pas pour tout couvrir. J'\u00e9cris quand un sujet m\u00e9rite d'\u00eatre trait\u00e9 correctement.</p>",
    edu_editorial: "<p>Mon parcours acad\u00e9mique a \u00e9t\u00e9 construit autour d'une contrainte unique : chaque th\u00e9orie devait avoir une application concr\u00e8te en quelques semaines. Rejoindre l'IUT de Lens la m\u00eame ann\u00e9e que mon entr\u00e9e chez Planet Soar n'\u00e9tait pas une co\u00efncidence d'agenda \u2014 c'\u00e9tait pr\u00e9cis\u00e9ment le but. Trois ans d'alternance ont compress\u00e9 ce que la plupart des programmes \u00e9talent sur cinq ans, et la pression de cons\u00e9quences commerciales r\u00e9elles a fait que l'apprentissage est rest\u00e9 d'une mani\u00e8re qu'une salle de classe seule ne peut reproduire.</p><p>Le passage \u00e0 l'ISG Paris est venu au bon moment. L'alternance m'avait donn\u00e9 la profondeur d'ex\u00e9cution ; le MSc m'a donn\u00e9 le vocabulaire strat\u00e9gique pour formaliser ce que j'avais construit et planifier la suite. Le projet de th\u00e8se \u2014 un business plan complet pour une entreprise e-commerce B2C \u00e0 partir d'un capital de 15 000 \u20ac \u2014 n'est pas un exercice acad\u00e9mique. C'est le plan que j'ai l'intention d'utiliser.</p><p>Du Botswana, o\u00f9 j'ai termin\u00e9 mes \u00e9tudes secondaires, \u00e0 Lens, puis \u00e0 Paris : la g\u00e9ographie a chang\u00e9 mais la logique non. Chaque \u00e9tape a \u00e9t\u00e9 choisie parce qu'elle comblait une lacune sp\u00e9cifique.</p>",
    qua_editorial: "<p>Je poursuis les certifications pour une raison pr\u00e9cise : l'apprentissage structur\u00e9 m'oblige \u00e0 syst\u00e9matiser des connaissances que j'ai souvent acquises de mani\u00e8re intuitive, et ce processus de formalisation r\u00e9v\u00e8le des lacunes dont je n'avais pas conscience.</p><p>La certification HubSpot Digital Marketing a chang\u00e9 ma fa\u00e7on de penser le funnel complet \u2014 pas seulement l'acquisition de trafic mais toute la cha\u00eene du premier contact \u00e0 la vente conclue. La certification Google Analytics (GA4) a fait de moi un analyste plus rigoureux ; \u00eatre test\u00e9 sur la m\u00e9thodologie plut\u00f4t que sur l'interface signifiait devoir comprendre pourquoi les chiffres bougent, pas seulement comment les lire. La certification PMI vers laquelle je travaille concerne la livraison de projets \u2014 g\u00e9rer des lancements transversaux m'a appris qu'un cadre clair fait la diff\u00e9rence entre une mise en production qui atterrit et une qui d\u00e9rive.</p><p>Au-del\u00e0 des dipl\u00f4mes, c'est la discipline elle-m\u00eame qui compte. S'engager dans une \u00e9tude structur\u00e9e tout en op\u00e9rant en production aiguise votre rapport \u00e0 votre propre savoir \u2014 vous apprenez ce que vous comprenez vraiment par opposition \u00e0 ce que vous avez simplement d\u00e9j\u00e0 vu fonctionner.</p>",
  },
};

export default content;
