/**
 * fetch-content.js — Melvyn Cross Portfolio
 *
 * Runs at Vercel build time (buildCommand in vercel.json).
 * Fetches the portfolio content document from Sanity CMS and writes
 * a fresh content.js to the project root.
 *
 * If Sanity is unreachable or the document doesn't exist yet, exits cleanly
 * so Vercel falls back to the committed content.js (no build failure).
 *
 * Usage:
 *   node scripts/fetch-content.js
 *
 * Required env var:
 *   SANITY_READ_TOKEN   — Viewer token (read-only) from Sanity project settings
 *   SANITY_PROJECT_ID   — optional override (defaults to p4gxllem)
 *   SANITY_DATASET      — optional override (defaults to production)
 */

import { createClient } from '@sanity/client';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const PROJECT_ID = process.env.SANITY_PROJECT_ID || 'p4gxllem';
const DATASET    = process.env.SANITY_DATASET    || 'production';
const TOKEN      = process.env.SANITY_READ_TOKEN;

if (!TOKEN) {
  console.warn('[fetch-content] SANITY_READ_TOKEN not set — using committed fallback content.js');
  process.exit(0);
}

const client = createClient({
  projectId:  PROJECT_ID,
  dataset:    DATASET,
  useCdn:     false,       // always fetch fresh at build time
  apiVersion: '2024-01-01',
  token:      TOKEN,
});

async function main() {
  console.log(`[fetch-content] Fetching from Sanity (project: ${PROJECT_ID}, dataset: ${DATASET})…`);

  let doc;
  try {
    doc = await client.fetch(`*[_id == "siteContent"][0]`);
  } catch (err) {
    console.warn('[fetch-content] Sanity fetch failed — using committed fallback content.js');
    console.warn('[fetch-content]', err.message);
    process.exit(0); // clean exit: Vercel uses the committed content.js
  }

  if (!doc) {
    console.warn('[fetch-content] No content document found in Sanity yet — using committed fallback content.js');
    console.warn('[fetch-content] Seed the document via: cd studio && npm run dev → create Portfolio Content document');
    process.exit(0);
  }

  // Helper: safely retrieve a localized string, empty string if missing
  const loc = (field, lang) => (doc[field] && doc[field][lang]) != null
    ? doc[field][lang]
    : '';

  const generated = `/* ============================================================
   MELVYN CROSS — CONTENT LAYER  (auto-generated)
   Generated by scripts/fetch-content.js at build time.
   Source: https://p4gxllem.sanity.studio
   DO NOT edit this file directly — edit content in Sanity Studio.
   ============================================================ */

const content = {
  en: {
    /* ── NAV ── */
    nav_location: ${JSON.stringify(loc('nav_location', 'en'))},

    /* ── 01. HERO ── */
    hero_label: ${JSON.stringify(loc('hero_label', 'en'))},
    hero_word_1: ${JSON.stringify(loc('hero_word_1', 'en'))},
    hero_word_2: ${JSON.stringify(loc('hero_word_2', 'en'))},
    hero_caption_1: ${JSON.stringify(loc('hero_caption_1', 'en'))},
    hero_caption_2: ${JSON.stringify(loc('hero_caption_2', 'en'))},

    /* ── 02. THE NUMBER ── */
    number_label: ${JSON.stringify(loc('number_label', 'en'))},
    number_year: ${JSON.stringify(loc('number_year', 'en'))},
    number_target: ${doc.number_target != null ? doc.number_target : 1600000},
    number_caption: ${JSON.stringify(loc('number_caption', 'en'))},

    /* ── 03. THE BEGINNING ── */
    beginning_chapter: ${JSON.stringify(loc('beginning_chapter', 'en'))},
    beginning_chapter_name: ${JSON.stringify(loc('beginning_chapter_name', 'en'))},
    beginning_title: ${JSON.stringify(loc('beginning_title', 'en'))},
    beginning_lead: ${JSON.stringify(loc('beginning_lead', 'en'))},
    beginning_p1: ${JSON.stringify(loc('beginning_p1', 'en'))},
    beginning_p2: ${JSON.stringify(loc('beginning_p2', 'en'))},

    /* ── 04. WHAT I BUILT ── */
    built_chapter: ${JSON.stringify(loc('built_chapter', 'en'))},
    built_title: ${JSON.stringify(loc('built_title', 'en'))},
    built_intro: ${JSON.stringify(loc('built_intro', 'en'))},
    stat_1_label: ${JSON.stringify(loc('stat_1_label', 'en'))},
    stat_1_note: ${JSON.stringify(loc('stat_1_note', 'en'))},
    stat_2_label: ${JSON.stringify(loc('stat_2_label', 'en'))},
    stat_2_note: ${JSON.stringify(loc('stat_2_note', 'en'))},
    stat_3_label: ${JSON.stringify(loc('stat_3_label', 'en'))},
    stat_3_note: ${JSON.stringify(loc('stat_3_note', 'en'))},
    stat_4_label: ${JSON.stringify(loc('stat_4_label', 'en'))},
    stat_4_note: ${JSON.stringify(loc('stat_4_note', 'en'))},
    stat_5_label: ${JSON.stringify(loc('stat_5_label', 'en'))},
    stat_5_note: ${JSON.stringify(loc('stat_5_note', 'en'))},
    stat_6_label: ${JSON.stringify(loc('stat_6_label', 'en'))},
    stat_6_note: ${JSON.stringify(loc('stat_6_note', 'en'))},

    /* ── 05. THE DEALS ── */
    deals_chapter: ${JSON.stringify(loc('deals_chapter', 'en'))},
    deals_title: ${JSON.stringify(loc('deals_title', 'en'))},
    deal_1_route: ${JSON.stringify(loc('deal_1_route', 'en'))},
    deal_1_name: ${JSON.stringify(loc('deal_1_name', 'en'))},
    deal_1_story: ${JSON.stringify(loc('deal_1_story', 'en'))},
    deal_2_route: ${JSON.stringify(loc('deal_2_route', 'en'))},
    deal_2_name: ${JSON.stringify(loc('deal_2_name', 'en'))},
    deal_2_story: ${JSON.stringify(loc('deal_2_story', 'en'))},

    /* ── 06. FASEP ── */
    fasep_chapter: ${JSON.stringify(loc('fasep_chapter', 'en'))},
    fasep_when: ${JSON.stringify(loc('fasep_when', 'en'))},
    fasep_title: ${JSON.stringify(loc('fasep_title', 'en'))},
    fasep_lead: ${JSON.stringify(loc('fasep_lead', 'en'))},
    fasep_p1: ${JSON.stringify(loc('fasep_p1', 'en'))},
    fasep_aside: ${JSON.stringify(loc('fasep_aside', 'en'))},

    /* ── 07. WHAT I BRING ── */
    bring_chapter: ${JSON.stringify(loc('bring_chapter', 'en'))},
    bring_title: ${JSON.stringify(loc('bring_title', 'en'))},
    bring_col1_title: ${JSON.stringify(loc('bring_col1_title', 'en'))},
    bring_col2_title: ${JSON.stringify(loc('bring_col2_title', 'en'))},
    bring_col3_title: ${JSON.stringify(loc('bring_col3_title', 'en'))},

    /* ── 08. CONTACT ── */
    contact_pre: ${JSON.stringify(loc('contact_pre', 'en'))},
    contact_cta: ${JSON.stringify(loc('contact_cta', 'en'))},
    contact_cv: ${JSON.stringify(loc('contact_cv', 'en'))},

    /* ── FOOTER ── */
    foot_built: ${JSON.stringify(loc('foot_built', 'en'))},

    /* ── PORTRAIT ── */
    portrait_alt: ${JSON.stringify(loc('portrait_alt', 'en'))},
    portrait_placeholder: ${JSON.stringify(loc('portrait_placeholder', 'en'))},
  },

  fr: {
    /* ── NAV ── */
    nav_location: ${JSON.stringify(loc('nav_location', 'fr'))},

    /* ── 01. HERO ── */
    hero_label: ${JSON.stringify(loc('hero_label', 'fr'))},
    hero_word_1: ${JSON.stringify(loc('hero_word_1', 'fr'))},
    hero_word_2: ${JSON.stringify(loc('hero_word_2', 'fr'))},
    hero_caption_1: ${JSON.stringify(loc('hero_caption_1', 'fr'))},
    hero_caption_2: ${JSON.stringify(loc('hero_caption_2', 'fr'))},

    /* ── 02. THE NUMBER ── */
    number_label: ${JSON.stringify(loc('number_label', 'fr'))},
    number_year: ${JSON.stringify(loc('number_year', 'fr'))},
    number_target: ${doc.number_target != null ? doc.number_target : 1600000},
    number_caption: ${JSON.stringify(loc('number_caption', 'fr'))},

    /* ── 03. THE BEGINNING ── */
    beginning_chapter: ${JSON.stringify(loc('beginning_chapter', 'fr'))},
    beginning_chapter_name: ${JSON.stringify(loc('beginning_chapter_name', 'fr'))},
    beginning_title: ${JSON.stringify(loc('beginning_title', 'fr'))},
    beginning_lead: ${JSON.stringify(loc('beginning_lead', 'fr'))},
    beginning_p1: ${JSON.stringify(loc('beginning_p1', 'fr'))},
    beginning_p2: ${JSON.stringify(loc('beginning_p2', 'fr'))},

    /* ── 04. WHAT I BUILT ── */
    built_chapter: ${JSON.stringify(loc('built_chapter', 'fr'))},
    built_title: ${JSON.stringify(loc('built_title', 'fr'))},
    built_intro: ${JSON.stringify(loc('built_intro', 'fr'))},
    stat_1_label: ${JSON.stringify(loc('stat_1_label', 'fr'))},
    stat_1_note: ${JSON.stringify(loc('stat_1_note', 'fr'))},
    stat_2_label: ${JSON.stringify(loc('stat_2_label', 'fr'))},
    stat_2_note: ${JSON.stringify(loc('stat_2_note', 'fr'))},
    stat_3_label: ${JSON.stringify(loc('stat_3_label', 'fr'))},
    stat_3_note: ${JSON.stringify(loc('stat_3_note', 'fr'))},
    stat_4_label: ${JSON.stringify(loc('stat_4_label', 'fr'))},
    stat_4_note: ${JSON.stringify(loc('stat_4_note', 'fr'))},
    stat_5_label: ${JSON.stringify(loc('stat_5_label', 'fr'))},
    stat_5_note: ${JSON.stringify(loc('stat_5_note', 'fr'))},
    stat_6_label: ${JSON.stringify(loc('stat_6_label', 'fr'))},
    stat_6_note: ${JSON.stringify(loc('stat_6_note', 'fr'))},

    /* ── 05. THE DEALS ── */
    deals_chapter: ${JSON.stringify(loc('deals_chapter', 'fr'))},
    deals_title: ${JSON.stringify(loc('deals_title', 'fr'))},
    deal_1_route: ${JSON.stringify(loc('deal_1_route', 'fr'))},
    deal_1_name: ${JSON.stringify(loc('deal_1_name', 'fr'))},
    deal_1_story: ${JSON.stringify(loc('deal_1_story', 'fr'))},
    deal_2_route: ${JSON.stringify(loc('deal_2_route', 'fr'))},
    deal_2_name: ${JSON.stringify(loc('deal_2_name', 'fr'))},
    deal_2_story: ${JSON.stringify(loc('deal_2_story', 'fr'))},

    /* ── 06. FASEP ── */
    fasep_chapter: ${JSON.stringify(loc('fasep_chapter', 'fr'))},
    fasep_when: ${JSON.stringify(loc('fasep_when', 'fr'))},
    fasep_title: ${JSON.stringify(loc('fasep_title', 'fr'))},
    fasep_lead: ${JSON.stringify(loc('fasep_lead', 'fr'))},
    fasep_p1: ${JSON.stringify(loc('fasep_p1', 'fr'))},
    fasep_aside: ${JSON.stringify(loc('fasep_aside', 'fr'))},

    /* ── 07. WHAT I BRING ── */
    bring_chapter: ${JSON.stringify(loc('bring_chapter', 'fr'))},
    bring_title: ${JSON.stringify(loc('bring_title', 'fr'))},
    bring_col1_title: ${JSON.stringify(loc('bring_col1_title', 'fr'))},
    bring_col2_title: ${JSON.stringify(loc('bring_col2_title', 'fr'))},
    bring_col3_title: ${JSON.stringify(loc('bring_col3_title', 'fr'))},

    /* ── 08. CONTACT ── */
    contact_pre: ${JSON.stringify(loc('contact_pre', 'fr'))},
    contact_cta: ${JSON.stringify(loc('contact_cta', 'fr'))},
    contact_cv: ${JSON.stringify(loc('contact_cv', 'fr'))},

    /* ── FOOTER ── */
    foot_built: ${JSON.stringify(loc('foot_built', 'fr'))},

    /* ── PORTRAIT ── */
    portrait_alt: ${JSON.stringify(loc('portrait_alt', 'fr'))},
    portrait_placeholder: ${JSON.stringify(loc('portrait_placeholder', 'fr'))},
  },
};

export default content;
`;

  const outPath = join(__dirname, '..', 'content.js');
  writeFileSync(outPath, generated, 'utf8');
  console.log('[fetch-content] ✅ content.js written from Sanity data');
}

main().catch((err) => {
  console.error('[fetch-content] Script crashed — using committed fallback content.js');
  console.error(err.message);
  process.exit(0); // clean exit, never fail the Vercel build
});
