/**
 * fetch-content.js — Melvyn Cross Portfolio
 *
 * Runs at Vercel build time (buildCommand in vercel.json).
 * Fetches all singleton content documents from Sanity CMS and writes
 * a fresh content.js to the project root.
 *
 * If Sanity is unreachable or a document doesn't exist yet, exits cleanly
 * so Vercel falls back to the committed content.js (no build failure).
 *
 * Usage:
 *   node scripts/fetch-content.js
 *
 * Required env var:
 *   SANITY_READ_TOKEN   — Viewer token (read-only) from Sanity project settings
 *   SANITY_PROJECT_ID   — optional override (defaults to p4gxllem)
 *   SANITY_DATASET      — optional override (defaults to production)
 */

import { createClient } from '@sanity/client';
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const __dirname = dirname(fileURLToPath(import.meta.url));

const PROJECT_ID = process.env.SANITY_PROJECT_ID || 'p4gxllem';
const DATASET    = process.env.SANITY_DATASET    || 'production';
const TOKEN      = process.env.SANITY_READ_TOKEN;

if (!TOKEN) {
  console.warn('[fetch-content] SANITY_READ_TOKEN not set — using committed fallback content.js');
  process.exit(0);
}

const client = createClient({
  projectId:  PROJECT_ID,
  dataset:    DATASET,
  useCdn:     false,       // always fetch fresh at build time
  apiVersion: '2024-01-01',
  token:      TOKEN,
});

async function main() {
  console.log(`[fetch-content] Fetching from Sanity (project: ${PROJECT_ID}, dataset: ${DATASET})…`);

  let doc, eduDoc, quaDoc, cpDoc, blDoc;
  try {
    [doc, eduDoc, quaDoc, cpDoc, blDoc] = await Promise.all([
      client.fetch(`*[_id == "siteContent"][0]`),
      client.fetch(`*[_id == "educationContent"][0]`),
      client.fetch(`*[_id == "qualificationsContent"][0]`),
      client.fetch(`*[_id == "contactPageContent"][0]`),
      client.fetch(`*[_id == "blogPageContent"][0]`),
    ]);
  } catch (err) {
    console.warn('[fetch-content] Sanity fetch failed — using committed fallback content.js');
    console.warn('[fetch-content]', err.message);
    process.exit(0);
  }

  if (!doc) {
    console.warn('[fetch-content] No homepage content document found in Sanity yet — using fallback content.js');
    process.exit(0);
  }

  // Helper: safely retrieve a localized field from any document
  const locFrom = (d, field, lang) => (d && d[field] && d[field][lang]) != null
    ? d[field][lang]
    : '';
  // Convenience wrappers per document
  const loc    = (field, lang) => locFrom(doc, field, lang);
  const edu    = (field, lang) => locFrom(eduDoc, field, lang);
  const qua    = (field, lang) => locFrom(quaDoc, field, lang);
  // Contact page has a mix of localized and plain string fields
  const cpLoc  = (field, lang) => locFrom(cpDoc, field, lang);
  const cpStr  = (field) => (cpDoc && cpDoc[field] != null) ? cpDoc[field] : '';
  const bl     = (field, lang) => locFrom(blDoc, field, lang);

  const generated = `/* ============================================================
   MELVYN CROSS — CONTENT LAYER  (auto-generated)
   Generated by scripts/fetch-content.js at build time.
   Source: https://p4gxllem.sanity.studio
   DO NOT edit this file directly — edit content in Sanity Studio.
   ============================================================ */

const content = {
  en: {
    /* ── NAV ── */
    nav_location: ${JSON.stringify(loc('nav_location', 'en'))},

    /* ── 01. HERO ── */
    hero_label: ${JSON.stringify(loc('hero_label', 'en'))},
    hero_word_1: ${JSON.stringify(loc('hero_word_1', 'en'))},
    hero_word_2: ${JSON.stringify(loc('hero_word_2', 'en'))},
    hero_caption_1: ${JSON.stringify(loc('hero_caption_1', 'en'))},
    hero_caption_2: ${JSON.stringify(loc('hero_caption_2', 'en'))},

    /* ── 02. THE NUMBER ── */
    number_label: ${JSON.stringify(loc('number_label', 'en'))},
    number_year: ${JSON.stringify(loc('number_year', 'en'))},
    number_target: ${doc.number_target != null ? doc.number_target : 1600000},
    number_caption: ${JSON.stringify(loc('number_caption', 'en'))},

    /* ── 03. THE BEGINNING ── */
    beginning_chapter: ${JSON.stringify(loc('beginning_chapter', 'en'))},
    beginning_chapter_name: ${JSON.stringify(loc('beginning_chapter_name', 'en'))},
    beginning_title: ${JSON.stringify(loc('beginning_title', 'en'))},
    beginning_lead: ${JSON.stringify(loc('beginning_lead', 'en'))},
    beginning_p1: ${JSON.stringify(loc('beginning_p1', 'en'))},
    beginning_p2: ${JSON.stringify(loc('beginning_p2', 'en'))},

    /* ── 04. WHAT I BUILT ── */
    built_chapter: ${JSON.stringify(loc('built_chapter', 'en'))},
    built_title: ${JSON.stringify(loc('built_title', 'en'))},
    built_intro: ${JSON.stringify(loc('built_intro', 'en'))},
    stat_1_label: ${JSON.stringify(loc('stat_1_label', 'en'))},
    stat_1_note: ${JSON.stringify(loc('stat_1_note', 'en'))},
    stat_2_label: ${JSON.stringify(loc('stat_2_label', 'en'))},
    stat_2_note: ${JSON.stringify(loc('stat_2_note', 'en'))},
    stat_3_label: ${JSON.stringify(loc('stat_3_label', 'en'))},
    stat_3_note: ${JSON.stringify(loc('stat_3_note', 'en'))},
    stat_4_label: ${JSON.stringify(loc('stat_4_label', 'en'))},
    stat_4_note: ${JSON.stringify(loc('stat_4_note', 'en'))},
    stat_5_label: ${JSON.stringify(loc('stat_5_label', 'en'))},
    stat_5_note: ${JSON.stringify(loc('stat_5_note', 'en'))},
    stat_6_label: ${JSON.stringify(loc('stat_6_label', 'en'))},
    stat_6_note: ${JSON.stringify(loc('stat_6_note', 'en'))},

    /* ── 05. THE DEALS ── */
    deals_chapter: ${JSON.stringify(loc('deals_chapter', 'en'))},
    deals_title: ${JSON.stringify(loc('deals_title', 'en'))},
    deal_1_route: ${JSON.stringify(loc('deal_1_route', 'en'))},
    deal_1_name: ${JSON.stringify(loc('deal_1_name', 'en'))},
    deal_1_story: ${JSON.stringify(loc('deal_1_story', 'en'))},
    deal_2_route: ${JSON.stringify(loc('deal_2_route', 'en'))},
    deal_2_name: ${JSON.stringify(loc('deal_2_name', 'en'))},
    deal_2_story: ${JSON.stringify(loc('deal_2_story', 'en'))},

    /* ── 06. FASEP ── */
    fasep_chapter: ${JSON.stringify(loc('fasep_chapter', 'en'))},
    fasep_when: ${JSON.stringify(loc('fasep_when', 'en'))},
    fasep_title: ${JSON.stringify(loc('fasep_title', 'en'))},
    fasep_lead: ${JSON.stringify(loc('fasep_lead', 'en'))},
    fasep_p1: ${JSON.stringify(loc('fasep_p1', 'en'))},
    fasep_aside: ${JSON.stringify(loc('fasep_aside', 'en'))},

    /* ── 07. WHAT I BRING ── */
    bring_chapter: ${JSON.stringify(loc('bring_chapter', 'en'))},
    bring_title: ${JSON.stringify(loc('bring_title', 'en'))},
    bring_col1_title: ${JSON.stringify(loc('bring_col1_title', 'en'))},
    bring_col2_title: ${JSON.stringify(loc('bring_col2_title', 'en'))},
    bring_col3_title: ${JSON.stringify(loc('bring_col3_title', 'en'))},

    /* ── 08. CONTACT ── */
    contact_pre: ${JSON.stringify(loc('contact_pre', 'en'))},
    contact_cta: ${JSON.stringify(loc('contact_cta', 'en'))},
    contact_cv: ${JSON.stringify(loc('contact_cv', 'en'))},

    /* ── FOOTER ── */
    foot_built: ${JSON.stringify(loc('foot_built', 'en'))},

    /* ── PORTRAIT ── */
    portrait_alt: ${JSON.stringify(loc('portrait_alt', 'en'))},
    portrait_placeholder: ${JSON.stringify(loc('portrait_placeholder', 'en'))},

    /* ── EDUCATION PAGE ── */
    edu_hero_pre: ${JSON.stringify(edu('edu_hero_pre', 'en'))},
    edu_hero_title: ${JSON.stringify(edu('edu_hero_title', 'en'))},
    edu_hero_sub: ${JSON.stringify(edu('edu_hero_sub', 'en'))},
    edu_hero_stat1_num: ${JSON.stringify(edu('edu_hero_stat1_num', 'en'))},
    edu_hero_stat1_txt: ${JSON.stringify(edu('edu_hero_stat1_txt', 'en'))},
    edu_hero_stat2_num: ${JSON.stringify(edu('edu_hero_stat2_num', 'en'))},
    edu_hero_stat2_txt: ${JSON.stringify(edu('edu_hero_stat2_txt', 'en'))},
    edu_hero_stat3_num: ${JSON.stringify(edu('edu_hero_stat3_num', 'en'))},
    edu_hero_stat3_txt: ${JSON.stringify(edu('edu_hero_stat3_txt', 'en'))},
    edu_isg_program: ${JSON.stringify(edu('edu_isg_program', 'en'))},
    edu_isg_dates: ${JSON.stringify(edu('edu_isg_dates', 'en'))},
    edu_isg_grade: ${JSON.stringify(edu('edu_isg_grade', 'en'))},
    edu_isg_desc1: ${JSON.stringify(edu('edu_isg_desc1', 'en'))},
    edu_isg_desc2: ${JSON.stringify(edu('edu_isg_desc2', 'en'))},
    edu_isg_opinion: ${JSON.stringify(edu('edu_isg_opinion', 'en'))},
    edu_isg_modules: ${JSON.stringify(edu('edu_isg_modules', 'en'))},
    edu_iut_program: ${JSON.stringify(edu('edu_iut_program', 'en'))},
    edu_iut_dates: ${JSON.stringify(edu('edu_iut_dates', 'en'))},
    edu_iut_employer: ${JSON.stringify(edu('edu_iut_employer', 'en'))},
    edu_iut_desc1: ${JSON.stringify(edu('edu_iut_desc1', 'en'))},
    edu_iut_desc2: ${JSON.stringify(edu('edu_iut_desc2', 'en'))},
    edu_iut_opinion: ${JSON.stringify(edu('edu_iut_opinion', 'en'))},
    edu_iut_modules: ${JSON.stringify(edu('edu_iut_modules', 'en'))},
    edu_gss_desc: ${JSON.stringify(edu('edu_gss_desc', 'en'))},

    /* ── QUALIFICATIONS PAGE ── */
    qua_hero_pre: ${JSON.stringify(qua('qua_hero_pre', 'en'))},
    qua_hero_title: ${JSON.stringify(qua('qua_hero_title', 'en'))},
    qua_hero_sub: ${JSON.stringify(qua('qua_hero_sub', 'en'))},
    qua_hero_stat1_num: ${JSON.stringify(qua('qua_hero_stat1_num', 'en'))},
    qua_hero_stat1_txt: ${JSON.stringify(qua('qua_hero_stat1_txt', 'en'))},
    qua_hero_stat2_num: ${JSON.stringify(qua('qua_hero_stat2_num', 'en'))},
    qua_hero_stat2_txt: ${JSON.stringify(qua('qua_hero_stat2_txt', 'en'))},
    qua_hero_stat3_num: ${JSON.stringify(qua('qua_hero_stat3_num', 'en'))},
    qua_hero_stat3_txt: ${JSON.stringify(qua('qua_hero_stat3_txt', 'en'))},
    qua_hs_name: ${JSON.stringify(qua('qua_hs_name', 'en'))},
    qua_hs_skills: ${JSON.stringify(qua('qua_hs_skills', 'en'))},
    qua_ga_name: ${JSON.stringify(qua('qua_ga_name', 'en'))},
    qua_ga_skills: ${JSON.stringify(qua('qua_ga_skills', 'en'))},
    qua_pmi_name: ${JSON.stringify(qua('qua_pmi_name', 'en'))},
    qua_pmi_status: ${JSON.stringify(qua('qua_pmi_status', 'en'))},
    qua_pmi_skills: ${JSON.stringify(qua('qua_pmi_skills', 'en'))},

    /* ── CONTACT PAGE ── */
    cp_hero_pre: ${JSON.stringify(cpLoc('cp_hero_pre', 'en'))},
    cp_hero_title: ${JSON.stringify(cpLoc('cp_hero_title', 'en'))},
    cp_email: ${JSON.stringify(cpStr('cp_email'))},
    cp_linkedin: ${JSON.stringify(cpStr('cp_linkedin'))},
    cp_linkedin_url: ${JSON.stringify(cpStr('cp_linkedin_url'))},
    cp_phone: ${JSON.stringify(cpStr('cp_phone'))},
    cp_phone_url: ${JSON.stringify(cpStr('cp_phone_url'))},

    /* ── BLOG PAGE ── */
    bl_hero_title: ${JSON.stringify(bl('bl_hero_title', 'en'))},
    bl_hero_desc: ${JSON.stringify(bl('bl_hero_desc', 'en'))},
  },

  fr: {
    /* ── NAV ── */
    nav_location: ${JSON.stringify(loc('nav_location', 'fr'))},

    /* ── 01. HERO ── */
    hero_label: ${JSON.stringify(loc('hero_label', 'fr'))},
    hero_word_1: ${JSON.stringify(loc('hero_word_1', 'fr'))},
    hero_word_2: ${JSON.stringify(loc('hero_word_2', 'fr'))},
    hero_caption_1: ${JSON.stringify(loc('hero_caption_1', 'fr'))},
    hero_caption_2: ${JSON.stringify(loc('hero_caption_2', 'fr'))},

    /* ── 02. THE NUMBER ── */
    number_label: ${JSON.stringify(loc('number_label', 'fr'))},
    number_year: ${JSON.stringify(loc('number_year', 'fr'))},
    number_target: ${doc.number_target != null ? doc.number_target : 1600000},
    number_caption: ${JSON.stringify(loc('number_caption', 'fr'))},

    /* ── 03. THE BEGINNING ── */
    beginning_chapter: ${JSON.stringify(loc('beginning_chapter', 'fr'))},
    beginning_chapter_name: ${JSON.stringify(loc('beginning_chapter_name', 'fr'))},
    beginning_title: ${JSON.stringify(loc('beginning_title', 'fr'))},
    beginning_lead: ${JSON.stringify(loc('beginning_lead', 'fr'))},
    beginning_p1: ${JSON.stringify(loc('beginning_p1', 'fr'))},
    beginning_p2: ${JSON.stringify(loc('beginning_p2', 'fr'))},

    /* ── 04. WHAT I BUILT ── */
    built_chapter: ${JSON.stringify(loc('built_chapter', 'fr'))},
    built_title: ${JSON.stringify(loc('built_title', 'fr'))},
    built_intro: ${JSON.stringify(loc('built_intro', 'fr'))},
    stat_1_label: ${JSON.stringify(loc('stat_1_label', 'fr'))},
    stat_1_note: ${JSON.stringify(loc('stat_1_note', 'fr'))},
    stat_2_label: ${JSON.stringify(loc('stat_2_label', 'fr'))},
    stat_2_note: ${JSON.stringify(loc('stat_2_note', 'fr'))},
    stat_3_label: ${JSON.stringify(loc('stat_3_label', 'fr'))},
    stat_3_note: ${JSON.stringify(loc('stat_3_note', 'fr'))},
    stat_4_label: ${JSON.stringify(loc('stat_4_label', 'fr'))},
    stat_4_note: ${JSON.stringify(loc('stat_4_note', 'fr'))},
    stat_5_label: ${JSON.stringify(loc('stat_5_label', 'fr'))},
    stat_5_note: ${JSON.stringify(loc('stat_5_note', 'fr'))},
    stat_6_label: ${JSON.stringify(loc('stat_6_label', 'fr'))},
    stat_6_note: ${JSON.stringify(loc('stat_6_note', 'fr'))},

    /* ── 05. THE DEALS ── */
    deals_chapter: ${JSON.stringify(loc('deals_chapter', 'fr'))},
    deals_title: ${JSON.stringify(loc('deals_title', 'fr'))},
    deal_1_route: ${JSON.stringify(loc('deal_1_route', 'fr'))},
    deal_1_name: ${JSON.stringify(loc('deal_1_name', 'fr'))},
    deal_1_story: ${JSON.stringify(loc('deal_1_story', 'fr'))},
    deal_2_route: ${JSON.stringify(loc('deal_2_route', 'fr'))},
    deal_2_name: ${JSON.stringify(loc('deal_2_name', 'fr'))},
    deal_2_story: ${JSON.stringify(loc('deal_2_story', 'fr'))},

    /* ── 06. FASEP ── */
    fasep_chapter: ${JSON.stringify(loc('fasep_chapter', 'fr'))},
    fasep_when: ${JSON.stringify(loc('fasep_when', 'fr'))},
    fasep_title: ${JSON.stringify(loc('fasep_title', 'fr'))},
    fasep_lead: ${JSON.stringify(loc('fasep_lead', 'fr'))},
    fasep_p1: ${JSON.stringify(loc('fasep_p1', 'fr'))},
    fasep_aside: ${JSON.stringify(loc('fasep_aside', 'fr'))},

    /* ── 07. WHAT I BRING ── */
    bring_chapter: ${JSON.stringify(loc('bring_chapter', 'fr'))},
    bring_title: ${JSON.stringify(loc('bring_title', 'fr'))},
    bring_col1_title: ${JSON.stringify(loc('bring_col1_title', 'fr'))},
    bring_col2_title: ${JSON.stringify(loc('bring_col2_title', 'fr'))},
    bring_col3_title: ${JSON.stringify(loc('bring_col3_title', 'fr'))},

    /* ── 08. CONTACT ── */
    contact_pre: ${JSON.stringify(loc('contact_pre', 'fr'))},
    contact_cta: ${JSON.stringify(loc('contact_cta', 'fr'))},
    contact_cv: ${JSON.stringify(loc('contact_cv', 'fr'))},

    /* ── FOOTER ── */
    foot_built: ${JSON.stringify(loc('foot_built', 'fr'))},

    /* ── PORTRAIT ── */
    portrait_alt: ${JSON.stringify(loc('portrait_alt', 'fr'))},
    portrait_placeholder: ${JSON.stringify(loc('portrait_placeholder', 'fr'))},

    /* ── EDUCATION PAGE ── */
    edu_hero_pre: ${JSON.stringify(edu('edu_hero_pre', 'fr'))},
    edu_hero_title: ${JSON.stringify(edu('edu_hero_title', 'fr'))},
    edu_hero_sub: ${JSON.stringify(edu('edu_hero_sub', 'fr'))},
    edu_hero_stat1_num: ${JSON.stringify(edu('edu_hero_stat1_num', 'fr'))},
    edu_hero_stat1_txt: ${JSON.stringify(edu('edu_hero_stat1_txt', 'fr'))},
    edu_hero_stat2_num: ${JSON.stringify(edu('edu_hero_stat2_num', 'fr'))},
    edu_hero_stat2_txt: ${JSON.stringify(edu('edu_hero_stat2_txt', 'fr'))},
    edu_hero_stat3_num: ${JSON.stringify(edu('edu_hero_stat3_num', 'fr'))},
    edu_hero_stat3_txt: ${JSON.stringify(edu('edu_hero_stat3_txt', 'fr'))},
    edu_isg_program: ${JSON.stringify(edu('edu_isg_program', 'fr'))},
    edu_isg_dates: ${JSON.stringify(edu('edu_isg_dates', 'fr'))},
    edu_isg_grade: ${JSON.stringify(edu('edu_isg_grade', 'fr'))},
    edu_isg_desc1: ${JSON.stringify(edu('edu_isg_desc1', 'fr'))},
    edu_isg_desc2: ${JSON.stringify(edu('edu_isg_desc2', 'fr'))},
    edu_isg_opinion: ${JSON.stringify(edu('edu_isg_opinion', 'fr'))},
    edu_isg_modules: ${JSON.stringify(edu('edu_isg_modules', 'fr'))},
    edu_iut_program: ${JSON.stringify(edu('edu_iut_program', 'fr'))},
    edu_iut_dates: ${JSON.stringify(edu('edu_iut_dates', 'fr'))},
    edu_iut_employer: ${JSON.stringify(edu('edu_iut_employer', 'fr'))},
    edu_iut_desc1: ${JSON.stringify(edu('edu_iut_desc1', 'fr'))},
    edu_iut_desc2: ${JSON.stringify(edu('edu_iut_desc2', 'fr'))},
    edu_iut_opinion: ${JSON.stringify(edu('edu_iut_opinion', 'fr'))},
    edu_iut_modules: ${JSON.stringify(edu('edu_iut_modules', 'fr'))},
    edu_gss_desc: ${JSON.stringify(edu('edu_gss_desc', 'fr'))},

    /* ── QUALIFICATIONS PAGE ── */
    qua_hero_pre: ${JSON.stringify(qua('qua_hero_pre', 'fr'))},
    qua_hero_title: ${JSON.stringify(qua('qua_hero_title', 'fr'))},
    qua_hero_sub: ${JSON.stringify(qua('qua_hero_sub', 'fr'))},
    qua_hero_stat1_num: ${JSON.stringify(qua('qua_hero_stat1_num', 'fr'))},
    qua_hero_stat1_txt: ${JSON.stringify(qua('qua_hero_stat1_txt', 'fr'))},
    qua_hero_stat2_num: ${JSON.stringify(qua('qua_hero_stat2_num', 'fr'))},
    qua_hero_stat2_txt: ${JSON.stringify(qua('qua_hero_stat2_txt', 'fr'))},
    qua_hero_stat3_num: ${JSON.stringify(qua('qua_hero_stat3_num', 'fr'))},
    qua_hero_stat3_txt: ${JSON.stringify(qua('qua_hero_stat3_txt', 'fr'))},
    qua_hs_name: ${JSON.stringify(qua('qua_hs_name', 'fr'))},
    qua_hs_skills: ${JSON.stringify(qua('qua_hs_skills', 'fr'))},
    qua_ga_name: ${JSON.stringify(qua('qua_ga_name', 'fr'))},
    qua_ga_skills: ${JSON.stringify(qua('qua_ga_skills', 'fr'))},
    qua_pmi_name: ${JSON.stringify(qua('qua_pmi_name', 'fr'))},
    qua_pmi_status: ${JSON.stringify(qua('qua_pmi_status', 'fr'))},
    qua_pmi_skills: ${JSON.stringify(qua('qua_pmi_skills', 'fr'))},

    /* ── CONTACT PAGE ── */
    cp_hero_pre: ${JSON.stringify(cpLoc('cp_hero_pre', 'fr'))},
    cp_hero_title: ${JSON.stringify(cpLoc('cp_hero_title', 'fr'))},
    cp_email: ${JSON.stringify(cpStr('cp_email'))},
    cp_linkedin: ${JSON.stringify(cpStr('cp_linkedin'))},
    cp_linkedin_url: ${JSON.stringify(cpStr('cp_linkedin_url'))},
    cp_phone: ${JSON.stringify(cpStr('cp_phone'))},
    cp_phone_url: ${JSON.stringify(cpStr('cp_phone_url'))},

    /* ── BLOG PAGE ── */
    bl_hero_title: ${JSON.stringify(bl('bl_hero_title', 'fr'))},
    bl_hero_desc: ${JSON.stringify(bl('bl_hero_desc', 'fr'))},
  },
};

export default content;
`;

  const outPath = join(__dirname, '..', 'content.js');
  writeFileSync(outPath, generated, 'utf8');
  console.log('[fetch-content] ✅ content.js written from Sanity data (homepage + 4 sub-pages)');

  // ── Regenerate sitemap.xml with live blog posts ──────────────────────────
  await generateSitemap();
}

async function generateSitemap() {
  const today = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

  // Fetch all published blog posts
  let posts = [];
  try {
    posts = await client.fetch(
      `*[_type == "post" && defined(publishedAt)] | order(publishedAt desc) { slug, publishedAt, _updatedAt }`
    );
    console.log(`[fetch-content] Found ${posts.length} blog post(s) for sitemap`);
  } catch (err) {
    console.warn('[fetch-content] Could not fetch posts for sitemap — using static pages only');
    console.warn('[fetch-content]', err.message);
  }

  const ORIGIN = 'https://melvyncross.com';

  // Static pages
  const staticPages = [
    { url: `${ORIGIN}/`,               lastmod: today, changefreq: 'monthly',  priority: '1.0' },
    { url: `${ORIGIN}/blog`,           lastmod: today, changefreq: 'weekly',   priority: '0.9' },
    { url: `${ORIGIN}/contact`,        lastmod: today, changefreq: 'yearly',   priority: '0.8' },
    { url: `${ORIGIN}/education`,      lastmod: today, changefreq: 'yearly',   priority: '0.7' },
    { url: `${ORIGIN}/qualifications`, lastmod: today, changefreq: 'yearly',   priority: '0.7' },
    { url: `${ORIGIN}/experiences`,    lastmod: today, changefreq: 'yearly',   priority: '0.6' },
    { url: `${ORIGIN}/books`,          lastmod: today, changefreq: 'monthly',  priority: '0.6' },
    { url: `${ORIGIN}/privacy`,        lastmod: today, changefreq: 'yearly',   priority: '0.3' },
  ];

  // Blog post pages
  const postPages = posts.map(p => ({
    url: `${ORIGIN}/post?slug=${encodeURIComponent(p.slug.current)}`,
    lastmod: (p._updatedAt || p.publishedAt || today).slice(0, 10),
    changefreq: 'monthly',
    priority: '0.8',
  }));

  const allPages = [...staticPages, ...postPages];

  const urlEntries = allPages.map(page => `
  <url>
    <loc>${page.url}</loc>
    <lastmod>${page.lastmod}</lastmod>
    <changefreq>${page.changefreq}</changefreq>
    <priority>${page.priority}</priority>
    <xhtml:link rel="alternate" hreflang="en" href="${page.url}"/>
    <xhtml:link rel="alternate" hreflang="fr" href="${page.url}"/>
    <xhtml:link rel="alternate" hreflang="x-default" href="${page.url}"/>
  </url>`).join('');

  const sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${urlEntries}
</urlset>
`;

  const sitemapPath = join(__dirname, '..', 'sitemap.xml');
  writeFileSync(sitemapPath, sitemap, 'utf8');
  console.log(`[fetch-content] ✅ sitemap.xml written — ${allPages.length} URLs (${posts.length} blog posts)`);
}

main().catch((err) => {
  console.error('[fetch-content] Script crashed — using committed fallback content.js');
  console.error(err.message);
  process.exit(0); // clean exit, never fail the Vercel build
});
